/**
 * 公共样式表
 *Created by qiaozm on 2018/5/16
 */
import Util from 'ygzycomponent/tools/Util';
import {OS} from '../../common/constant';
import {StyleSheet} from 'react-native';

const CommonStyle = StyleSheet.create({
    popOpacity:{
        width:Util.size.width,
        height:Util.size.height,
        backgroundColor:'#000',
        opacity:0.5
    },
    posit:{
        position:'absolute',
        top:0,
        left:0
    },
    fontYgzy:{
        fontFamily:(OS === 'ios')?null:'ygzyFont' //自定义￥符号
    },
    fontTenEven:{
        fontSize:9
    },
    fontTenen:{
        fontSize:10
    },
    fontTene:{
        fontSize:11
    },
    fontTenTwo:{
        fontSize:12
    },
    fontThree:{
        fontSize:13
    },
    fontTenFour:{
        fontSize:14
    },
    fontTenFiv:{
        fontSize:15
    },
    fontTenSix:{
        fontSize:16
    },
    fontTenEig:{
        fontSize:18
    },
    colorThree:{
        color:'#333'
    },
    colorNomal:{
        color:'#5e5a57'
    },
    qianGray:{
        color:'#848484'
    },
    gray:{
        color:'#bcbcbc'
    },
    red:{
        color:'#f65e5d'
    },
    shenGray:{
        color:'#7684a4',
    },
    genGray:{
        color:'#969fb4'
    },
    danGray:{
        color:'#b0b0b0'
    },
    greenColor: {
        color: '#44c9d0'
    },
    nenGreenColor:{
        color:'#4cb071'
    },
    orange:{
        color:'#e58e13'
    },
    six:{
        color:'#666'
    },
    width:{
        width:Util.size.width
    },
    witeColor:{
        color:'#fff'
    },
    writeColor:{
        backgroundColor:'#fff'
    },
    textCenter:{
        textAlign:'center'
    },
    center:{
        justifyContent:'center',
        alignItems:'center'
    },
    row:{
        flexDirection:'row'
    },
    shaps:{
        height:10*Util.size.height/667,
        width:Util.size.width,
        backgroundColor:'#f0eff5'
    },
    marLeft:{
        marginLeft:Util.size.width/75
    },
    wrap:{
        flexWrap:'wrap'
    },
    title:{
        width:Util.size.width,
        paddingLeft:Util.size.width/25,
        paddingRight:Util.size.width/25,
        paddingTop:30*Util.size.width/667,
        paddingBottom:30*Util.size.width/667,
    },
    height:{
        paddingTop:30*Util.size.width/667,
        paddingBottom:30*Util.size.width/667,
    },
    /*合作模块*/
    artInTops:{
        width:11*Util.size.width/13,
        paddingBottom:15*Util.size.height/667,
        paddingTop:15*Util.size.height/667,
        paddingLeft:2*Util.size.width/75,
        paddingRight:2*Util.size.width/75,
        backgroundColor:'#fff',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:5,
        borderWidth:0.8,
        borderColor:'#d4d4d4',
        borderStyle:'dashed',
        marginBottom:11*Util.size.height/667
    },
    artInTop:{
        width:11*Util.size.width/13,
        paddingBottom:15*Util.size.height/667,
        paddingTop:15*Util.size.height/667,
        paddingLeft:2*Util.size.width/75,
        paddingRight:2*Util.size.width/75,
        backgroundColor:'#fff',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:5,
        borderWidth:0.8,
        borderColor:'#d4d4d4',
        borderStyle:'dashed',
        marginTop:11*Util.size.height/667,
        marginBottom:11*Util.size.height/667
    },
    conArt:{
        width:11*Util.size.width/13,
    },
    bgGray:{
        backgroundColor:'#f0eff5'
    },
    marRight:{
        marginRight:2*Util.size.width/75
    },
    padLeft:{
        paddingLeft:2*Util.size.width/75
    },
    commonWidth:{
        width:3*Util.size.width/75
    },
    borderBottom:{
        borderColor:'#d5d5d5',
        borderBottomWidth:Util.pixel
    },


});
export default CommonStyle;
